### ISSUE TITLE
Most devDependencies should be moved to dependencies

### ISSUE THREAD

**Issue by ilabacheuski** [Travix-International/eslint-config-travix#31]
Because the library itself is a config for eslint that means that all eslint-configs and plugins should be placed in dependency rather than in dependency.
For example:
```
"devDependencies": {
    "babel-eslint": "~8.2.6",
    "eslint": "~5.3.0",
    "eslint-config-airbnb": "~17.1.0",
    "eslint-plugin-import": "~2.14.0",
    "eslint-plugin-jsx-a11y": "~6.1.1",
    "eslint-plugin-react": "~7.11.1",
    "semantic-release": "~15.9.8",
    "simple-commit-message": "~4.0.3"
  },
```

I am not sure about last 2 of them, but everything other is crucial dependency, not for development.

This cause a bug, that after installation of this config you cannot lint with this config, because you miss dependency like `eslint-plugin-jsx-a11y`

**Comment by yurist38** [comment]
@ilabacheuski Thank you for pointing out to the issue! I've checked the possible options of handling the current problem and found that the most common way (and I think the best one so far) is to keep them as peer dependencies. For example, [airbnb](https://www.npmjs.com/package/eslint-config-airbnb) and some others do it in this way. Please review the PR https://github.com/Travix-International/eslint-config-travix/pull/32
